### ISSUE TITLE
question- updated version for celery 4.2?

### ISSUE THREAD

**Issue by jordotech** [RichardBronosky/celery_test#1]
Love this repo, is there an updated version out there?

A lot has changed since celery 3.1

Thanks

**Comment by RichardBronosky** [comment]
i have a project at work that might be a Celery candidate. If it is I will update this. Probably not otherwise. This little demo repos are something I do to document for myself what I learned during an investigation. The goal is simply to be able to repeat the result later and show it to a developer when I suggest they use a specific tech.

I'm pretty terrible at maintaining things.

**Comment by jordotech** [comment]
I did find this earlier today which was helpful: https://github.com/williln/celery-docker-example

Thanks, I think it was the teaching style that I liked about your demo, keep it up :)
